
############# SITE PROPERTIES #############

# localhost port (can be anything)
port: 4000

# used with localization. change to "japanese" or "german" if localizing.
language: english

# the output. in the _config_pdf.yml, this is "pdf". you can create conditions based on this property (such as navtab content that should appear in web but not pdf).
format: web

paginate: 5

# the little icon that appears in the browser window's tab
favicon: assets/favicon.ico

# home_url
home_url: https://noahjameschristiansen.github.io/template-information-site/
#home_url: http://localhost:4000/

# Source code url:
source_code_url: https://github.com/noahjameschristiansen/template-information-site

############# TOP NAVIGATION BAR ################

blog_logo: assets/blog_photo.png
blog_logo_alt_text: Description of the above image. make this meaningful! It's for visually impaired people and slow internet connections.

# make search bar appear in top nav?
search_in_topnav: true

############# AUTOMATED LINKS #############

# the links.html script requires you to list your sidebars here. this is if you're using managed links (see jekyllhowto-content-and-formatting.html#automatedlinks)
sidebars:
  - home
  - sample_subject
  - sample_time
  - tutorial

# determines whether the links.html script uses the jurl or hurl values in the sidebar data file
link_type: jurl

############# FEEDBACK BUTTON #############

# show feedback button in top nav bar?
show_feedback: true

# email address feedback gets sent to
feedback_email: test@test.com

############# EXCLUDE LIST #############
# these folders or files will not be included in the output. you can use wildcards with asterisks.
exclude:
  - Config
  - s3_website
  - _config_*
  - Gemfile*
  - serve_*
  - build_*
  - gem_*
  - prince-list.txt
  - jekyll-theme-doc-project*
  - pdf
  - mobi

############# DEFAULTS #############
# you can define default frontmatter values here. you can narrow the type down with subfolders (e.g., docs/myfolder).
# you might want to list your sidebar and product as default frontmatter values
# with translation, change topnav, footer (and sidebar) to use topnav_ja, footer_ja, generic_ja etc. for Japanese, or _de for german. you must have corresponding
# data files with those _ja or _de file names. Read more in jekyllhowto-localization.html.
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
      topnav: topnav
      footer: footer
      include_sidebar: true
  -
    scope:
      path: ""
      type: docs
    values:
      layout: document
      topnav: topnav
      footer: footer
      include_sidebar: true
     
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      topnav: topnav
      footer: footer
      include_sidebar: true
  -
    scope:
      path: ""
      type: search
    values:
      layout: default
      topnav: topnav
      footer: footer
      type: search
      sidebar: jekyllhowto

  -
    scope:
      path: "assets/images"
    values:
      image: true

##########  MARKDOWN PROCESS AND FILTER ##########
# leave these settings as is unless you want to use something other than kramdown Markdown

highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

########## SASS SETTINGS ##########
# used to define sass settings. leave as is.

 sass:
     style: compressed

############# COLLECTIONS #############
# used to define collections used in project. leave as is.

collections:
  docs:
    output: true

# gems and other configs
plugins:
  - jekyll-paginate
  - jekyll-replace-last

########## UI text ###############
# The UI text is separated into strings defined here to facilitate translation. Grouping them here also consolidates all UI text.
# Translate these for Japanese and German outputs.

uistring:
    title: Test Template Theme # title to appear in nav bar and page meta
    description: Description of the site # Displays as site description meta tag for site
    copyright: 2024 Test Website # appears in footer
    tableofcontents: Table of Contents # text that appears before in-page table of contents
    expandall: Expand All # appears as text in sidebar to expand all levels
    collapseall: Collapse All # appears as text in sidebar to collapse all levels
    search_placeholder_text: Search ... # appears as placeholder in search field
    no_search_results_found: No matches found. Try using other keywords?
    feedback_link_name: Feedback # name of Feedback link
    feedback_subject_line: Feedback # Auto-filled Subject of email
    feedback_body: I have some feedback for your template. # Auto-filled Body of email
    blog: Political Theory Blog # Name of blog displayed on the top of posts
    datetime_format: '%Y-%m-%d' # date time format
    continue_reading: Continue Reading... # continue reading on the bottom of docs
    continue_prev: <- Previous # Previous for bottom of docs
    continue_next: Next -> # Next for bottom of docs
    months:
        jan: January
        feb: February
        mar: March
        apr: April
        may: May
        jun: June
        jul: July
        aug: August
        sep: September
        oct: October
        nov: November
        dec: December
